# Setup
title: Emilie Naples
description: >
  Data Analyst & Analytics Specifications Architect
  
url: https://emilienaples.github.io
avatar: /images/Picture1.jpg 
paginate: 5
permalink: pretty
cover_image: /images/background2.jpg

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts/

linkedin:
  username: emilienaples
  card: summary
logo: logo.png
social:
  name: Emilie Naples
  links:
    - https://www.linkedin.com/in/emilienaples/
    - https://github.com/emilienaples
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Enabling disqus
# disqus: xxxxxx
